# Generated by Django 6.0.1 on 2026-02-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='set_option',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='option',
            field=models.CharField(choices=[('Single D20', 'Single D20'), ('Full set of 7', 'Full set of 7')], default='Single D20', max_length=20),
        ),
    ]
