# Generated by Django 6.0.1 on 2026-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_orderlineitem_set_option_orderlineitem_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='option',
            field=models.CharField(choices=[('single', 'Single D20'), ('set', 'Full set of 7')], default='single', max_length=10),
        ),
    ]
