# Generated by Django 6.0.1 on 2026-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_orderlineitem_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='option',
            field=models.CharField(choices=[('single', 'Single Item or Single D20'), ('set', 'Full dice set of 7')], default='single', max_length=10),
        ),
    ]
