# Generated by Django 6.0.1 on 2026-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='save_info',
            field=models.BooleanField(default=False),
        ),
    ]
