# Generated by Django 6.0.1 on 2026-02-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_save_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
