# Generated by Django 6.0.1 on 2026-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_productofthemonth_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productofthemonth',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='productofthemonth',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='productofthemonth',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='productofthemonth',
            unique_together={('year', 'month')},
        ),
    ]
