# Generated by Django 6.0.1 on 2026-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_productofthemonth_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productofthemonth',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Product of the Month', 'verbose_name_plural': 'Product of the Month'},
        ),
    ]
