# Generated by Django 6.0.1 on 2026-01-31 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testimonial_alter_productofthemonth_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
    ]
