# Generated by Django 6.0.1 on 2026-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactform',
            name='topic',
            field=models.CharField(choices=[('order', 'I have a question about my order'), ('materials', 'A question about materials or dice care'), ('returns', 'My loot arrived damaged/faulty'), ('technical', 'Report a glitch in the weave'), ('other', 'General feedback or tavern tales')], default='topic', max_length=20),
            preserve_default=False,
        ),
    ]
