# Generated by Django 6.0.1 on 2026-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contactform_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='topic',
            field=models.CharField(choices=[('order', 'I have a question about my order'), ('materials', 'A question about materials or dice care'), ('returns', 'My loot arrived damaged/faulty'), ('technical', 'Report a glitch in the weave'), ('other', 'General feedback or tavern tales')], max_length=20),
        ),
    ]
