# Generated by Django 6.0.1 on 2026-02-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_dice_set',
            field=models.BooleanField(default=False),
        ),
    ]
